### ISSUE TITLE
How fix error Dialect needs to be explicitly supplied as of v4.0.0

### ISSUE THREAD

**Issue by buiduongthe** [onwuvic/nest-blog-api#17]
Dear Onwuvic

I run project error "Dialect needs to be explicitly supplied as of v4.0.0"
How fix?

Thanks

**Comment by amouratoglou** [comment]
hi @buiduongthe you might not have installed on your system PostgreSQL.
It would be good to add this steps in the tut.

Make sure to install PostgreSQL on your device.

If you are using Mac is something like this:
on your console run:

`$ brew install postgres`

then install pg tools for node

`$ npm install -pg-tools`

create a server-create.js file:

```
var pgtools = require('pgtools');
const config = {
//here I used my computer username.
  user: 'yourusername',
  host: 'localhost',
  password: '1234',
  port: 5432,
};
pgtools.createdb(config, 'development_database_name', function(err, res) {
  if (err) {
    console.error(err);
    process.exit(-1);
  }
  console.log(res);
});

```

then run

`$ node server-create.js`

match the values with the ones of the .env file on the project
so that it connect your your newly created DB!
cheers

**Comment by onwuvic** [comment]
@buiduongthe Did you later find a way to fix the error?

**Comment by buiduongthe** [comment]
thanks @onwuvic and I'm sorry. I fixed error.
